server:
    port: 30001
    servlet:
        context-path: /boba
spring:
    application:
        name: portal-api
    redis: # redis 配置
        host: 172.31.18.99
        port: 6379
        database: 0
        password: 123321
        timeout: 1000ms
        lettuce:
            pool:
                enabled: true
                max-active: 8
                max-idle: 8
                min-idle: 0
                max-wait: -1ms
    mail:
        from: brewery.boba@gmail.com
        host: email-smtp.ap-southeast-1.amazonaws.com
        port: 465
        protocol: stmps
        username: AKIAVG5OF7CZHQCSI3N2
        password: BAa2tfZzroIkWnDMPJu20gQmWn+9ZoHkzIr/78a6OkNN

    datasource: #druid数据源配置
        druid:
            url: jdbc:mysql://database-1.c6i1s0ztcym8.ap-southeast-1.rds.amazonaws.com:3306/boba?useSSL=false&useUnicode=true&characterEncoding=utf8
            username: admin
            password: gwgjTfbsK*UJJwDV
            driver-class-name: com.mysql.cj.jdbc.Driver
            max-wait: 10000 #获取连接时最大等待时间，单位毫秒
            initial-size: 10 #初始化时建立物理连接的个数
            max-active: 100 #最大连接池数量
            min-idle: 10 #最小连接数
            time-between-eviction-runs-millis: 3600000 #检测连接的间隔时间
            min-evictable-idle-time-millis: 300000 #连接的最小生存时间
            test-while-idle: true  #检测连接是否有效
            test-on-borrow: false #申请连接时执行validationQuery检测连接是否有效，做了这个配置会降低性能
            validation-query: SELECT 1 #用来检测连接是否有效的sql
            filters: stat #监控统计用的filter:stat日志用的filter:log4j防御sql注入的filter:wall
            stat-view-servlet:
                url-pattern: /druid/*
                reset-enable: true #允许清空统计数据
                login-username: root #监控后台管理账号和密码
                login-password: root
            web-stat-filter:
                url-pattern: /*
                exclusions: "*.js,*.gif,*.jpg,*.bmp,*.png,*.css,*.ico,/druid/*"
mybatis:
    mapper-locations: classpath*:mapper/*Mapper.xml

logging:
    file:
        name: /cnb/log/${spring.application.name}.log
    logback:
        rollingpolicy:
            file-name-pattern: /cnb/log/${spring.application.name}.%d{yyyy-MM-dd}.%i.gz


owner:
    private:
        key: bcb80398e2ef7c966ba54304e0c64170d183c2c222bb2789d7b17510915ce817

telegram:
    token: 5012551789:AAHpZRuM_D5mJZvP_MRi9XQpH6Z-XG_Wkgw

encode:
    server: http://172.31.11.2:30001

staking:
    boba: 0x4a050E34174F982Bcb9731871b3Af9140841b463

meta-derby:
    baseUrl: https://api.derbygames.link